name: Build amd64

on:
  push:
    branches: [ master ]

jobs:
  build_amd64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y git make fakeroot binutils-arm-linux-gnueabihf gcc-arm-linux-gnueabihf dpkg-dev build-essential crossbuild-essential-armhf libgtk-3-dev libjson-glib-dev
      - name: Make
        run: make
      - name: Make DEB
        run: make pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gmcpil_latest_amd64.deb
          path: gmcpil_*.deb
